name: Test

on:
  workflow_dispatch:
  push:

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.100-preview.7
      - name: Initialize
        shell: pwsh
        run: .\New-Solution.ps1
      - name: Build
        shell: pwsh
        run: .\Build-Solution.ps1
