name: Test

on:
  workflow_dispatch:
  push:

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
      - name: Initialize
        shell: pwsh
        run: .\New-Solution.ps1 -ActionKeyword hoge -Author hoge -ProjectName hoge
      - name: Build
        shell: pwsh
        run: .\Build-Solution.ps1
